config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  unauthenticated do
    devise_scope :user do
      root to: 'home#index', as: 'home'
    end
  end
  authenticated :user do
    devise_scope :user do
      root to: 'feeds#index', as: 'feed'
    end
  end

  root to: 'feeds#index'
  resources :profiles, only: [:show, :edit, :update]
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  has_one :user
  accepts_nested_attributes_for :user
  delegate :name, :email, :gender, to: :user

  has_attached_file :photo, styles: { thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  extend Enumerize
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable, :trackable, :rememberable
  devise :database_authenticatable, :registerable,
         :recoverable, :validatable
  belongs_to :profile

  after_create :create_profile

  enumerize :gender, in: [:male, :female]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :infer_locale

  layout "landing"

  protected
  def infer_locale
    inferred_locale = http_accept_language.compatible_language_from(I18n.available_locales)
    I18n.locale = inferred_locale || I18n.default_locale
  end

end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  layout 'feed'
  
  def index
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  layout 'landing'
  
  def index
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  layout "feed"
  
  before_filter :authenticate_user!

  def show
    @profile = Profile.find params[:id]
  end

  def edit
    if current_user.profile_id.to_s != params[:id]
      redirect_to root_path, alert: 'Not your profile'
    else
      @profile = current_user.profile
    end
  end

  def update
    if current_user.profile_id.to_s != params[:id]
      redirect_to root_path, alert: 'Not your profile'
    else
      @profile = current_user.profile
      if @profile.update_attributes profile_params
        redirect_to profile_path(@profile)
      else
        render :edit
      end
    end
  end

  private
  def profile_params
    params.require(:profile).permit(
      :photo,
      user_attributes: [:id, :name, :email, :gender]
      )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def flash_to_bs_alert name
    case name
    when "notice"
      "alert-success"
    when "alert"
      "alert-danger"
    when "flash"
      "alert-info"
    else
      "alert-warning"
    end
  end

end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/feeds/index.html.erb
Feed index

app/views/home/index.html.erb
<h1 class="cover-heading">Welcome</h1>
<p class="lead">To the anti-social network! It was designed to be a more functional, useful, productive, secure and non-addictive experience. No more meaningless friendships, forced interactions and unnecessary conversations.</p>
<p class="lead">
  <%= link_to 'Sign-in', new_user_session_path, class: "btn btn-lg btn-default", accesskey: "i" %></br>
  <span class="legend">or press alt+i</span>
</p>

app/views/layouts/feed.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SocialNw</title>
    <%= stylesheet_link_tag    'feed', media: 'all', 'data-turbolinks-track' => true %>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render 'layouts/feed/nav' %>
    <div class="container">
      <%= render 'layouts/feed/head' %>
      <%= render 'layouts/shared/flash' %>
      <div class="row">
        <div class="col-sm-8 main">
          <%= yield %>
        </div>
        <div class="col-sm-3 col-sm-offset-1 sidebar">
          <%= render 'layouts/feed/sidebar' %>
        </div>
      </div>
    </div>
    <%= render 'layouts/feed/foot' %>
    <%= javascript_include_tag 'feed', 'data-turbolinks-track' => true %>
  </body>
</html>

app/views/layouts/feed/_foot.html.erb
<div class="footer">
  <p>
    Blog template built for
    <a href="http://getbootstrap.com">Bootstrap</a> by 
    <a href="https://twitter.com/mdo">@mdo</a>.
  </p>
  <p>
    <a href="#">Back to top</a>
  </p>
</div>

app/views/layouts/feed/_head.html.erb
<header class="header">
</header>

app/views/layouts/feed/_nav.html.erb
<div class="masthead">
  <div class="container">
    <nav class="nav">
      <%= link_to t('nav.home'), feed_path, class: 'nav-item' %>
      <%= link_to t('nav.profile'), profile_path(current_user.profile), class: 'nav-item' %>
      <%= link_to t('nav.sign_out'), destroy_user_session_path, class: 'nav-item', method: :delete %>
    </nav>
  </div>
</div>

app/views/layouts/feed/_sidebar.html.erb
<div class="sidebar-module sidebar-module-inset">
  <h4>About</h4>
  <p>Etiam porta <em>sem malesuada magna</em> mollis euismod. Cras mattis consectetur purus sit amet fermentum. Aenean lacinia bibendum nulla sed consectetur.</p>
</div>
<div class="sidebar-module">
  <h4>Archives</h4>
  <ol class="list-unstyled">
    <li><a href="#">January 2014</a></li>
    <li><a href="#">December 2013</a></li>
    <li><a href="#">November 2013</a></li>
    <li><a href="#">October 2013</a></li>
    <li><a href="#">September 2013</a></li>
    <li><a href="#">August 2013</a></li>
    <li><a href="#">July 2013</a></li>
    <li><a href="#">June 2013</a></li>
    <li><a href="#">May 2013</a></li>
    <li><a href="#">April 2013</a></li>
    <li><a href="#">March 2013</a></li>
    <li><a href="#">February 2013</a></li>
  </ol>
</div>
<div class="sidebar-module">
  <h4>Elsewhere</h4>
  <ol class="list-unstyled">
    <li><a href="#">GitHub</a></li>
    <li><a href="#">Twitter</a></li>
    <li><a href="#">Facebook</a></li>
  </ol>
</div>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SocialNw</title>
    <%= stylesheet_link_tag    'landing', media: 'all', 'data-turbolinks-track' => true %>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="site-wrapper">
      <div class="site-wrapper-inner">
        <div class="cover-container">
          <%= render 'layouts/landing/head' %>
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
          <div class="inner cover">
            <%= yield %>
          </div>
          <%= render 'layouts/landing/foot' %>
        </div>
      </div>
    </div>
    <%= javascript_include_tag 'landing', 'data-turbolinks-track' => true %>
  </body>
</html>

app/views/layouts/landing/_foot.html.erb
<div class="mastfoot">
  <div class="inner">
    <p>Cover template for <a href="http://getbootstrap.com">Bootstrap</a>, by <a href="https://twitter.com/mdo">@mdo</a>.</p>
  </div>
</div>

app/views/layouts/landing/_head.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Cover</h3>
    <ul class="nav masthead-nav">
      
    </ul>
  </div>
</div>

app/views/layouts/shared/_flash.html.erb
<% flash.each do |name, msg| %>
  <div class="alert <%= flash_to_bs_alert(name) %>">
    <button type="button" class="close" "data-dismiss"="alert" "aria-hidden"="true">
      &times;
    </button>
    <%= msg %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<form role="form">

</form>

<%= form_for @profile, role: 'form', html: { multipart: true } do |f| %>
  <%= f.fields_for :user do |uf| %>
    <div class="form-group">
      <%= uf.label :email, "Email Address" %>
      <%= uf.email_field :email, required: true, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= uf.label :name, "Name" %>
      <%= uf.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= uf.label :gender, "Gender" %>
      <%= uf.select :gender, User.gender.options, {include_blank: true}, {class: 'form-control'} %>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.label :photo, "Photo" %>
    <%= f.file_field :photo, class: 'form-control' %>
  </div>
  <%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/profiles/show.html.erb
<p class="pull-right">
  <%= link_to 'Editar', edit_profile_path(@profile) %>
</p>
<h1>Olá</h1>
<div>
  <p>Nome: <%= @profile.name %></p>
  <p>Email: <%= @profile.email %></p>
  <p>Sexo: <%= @profile.user.gender_text %></p>
  <p>Photo:<%= image_tag @profile.photo.url(:thumb) %></p>
</div>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>